version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backendprod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: mydatabase
      OPENAI_API_KEY: 
      ASSISTANTS_URL:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      GOOGLE_REDIRECT_URI:
      ACCESS_TOKEN_EXPIRE_MINUTES:
      JWT_SECRET: secret
      CLIENT_LOGIN_REDIRECT_URI: http://localhost:4173
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontendprod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "4173:4173"
    depends_on:
      - backendprod
    environment:
      PUBLIC_BUSINESS_LAYER_URL: http://localhost:8000
    command: npm run preview

volumes:
  postgres_data: